// ************************* This module is used to create the Welcome board. Kind of a brute force way to make it *************************

// ===== Create the new welcome board for a selected user
module.exports.getWelcomeBoard = function(userId) {
	var welcomeBoard = {
		"chat" : [],
		"created" : new Date(),
		"lastModified" : new Date(),
		"owner" : userId,
		"title" : "Welcome to BoardThing"
	};

	return welcomeBoard;
}

// create the boards that will be attached to the welcome board
module.exports.getWelcomeBoardCards = function(boardId) {
	var ObjectID = require('mongodb').ObjectID;
	
	var mainClusterId = new ObjectID();
	var mainCusterChild1 = new ObjectID();
	var mainCusterChild2 = new ObjectID();
	var mainCusterChild3 = new ObjectID();
	var mainCusterChild3Child = new ObjectID();
	var mainCusterChild4 = new ObjectID();
	var mainCusterChild5 = new ObjectID();
	var mainCusterChild6 = new ObjectID();
	var mainCusterChild6Child = new ObjectID();
	var secondCluster = new ObjectID();
	var secondClusterChild = new ObjectID();

	var welcomeCards = [{
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "Welcome to Boardthing!",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 31,
		"yPos" : 66,
		"zPos" : 4
	}, 
	{
		"_id" : mainCusterChild1,
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "This is a card.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 22,
		"yPos" : 102,
		"zPos" : 6
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "63337266-6c77-b29d-59d2-cd4e7e3a1eee.jpg",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "This is an image card (caption optional).",
		"type" : "image/jpeg",
		"votesReceived" : 0,
		"xPos" : 31,
		"yPos" : 181,
		"zPos" : 15
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "Just type and hit enter to create a card.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 28,
		"yPos" : 114,
		"zPos" : 12
	}, {
		"_id" : mainClusterId,
		"board": boardId,
		"children" : [mainCusterChild2, mainCusterChild3, mainCusterChild4, mainCusterChild5, mainCusterChild1, mainCusterChild6],
		"collapsed" : false,
		"comments" : [],
		"content" : "This is a group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 238,
		"yPos" : 58,
		"zPos" : 11
	}, {
		"_id" : mainCusterChild2,
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "Drag a card onto any other card and that will create a group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 302,
		"yPos" : 104,
		"zPos" : 1
	}, {
		"_id" : mainCusterChild3Child,
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "You can also drag a group into a group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainCusterChild3,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 296,
		"yPos" : 247,
		"zPos" : 1
	}, {
		"_id" : mainCusterChild3,
		"board": boardId,
		"children" : [mainCusterChild3Child],
		"collapsed" : true,
		"comments" : [],
		"content" : "This is another group. The little box in the corner shows how many cards are in the group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 10,
		"yPos" : 40,
		"zPos" : 2
	}, {
		"_id" : mainCusterChild4,
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "Double-click a group's title to expand and collapse the group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 10,
		"yPos" : 40,
		"zPos" : 3
	}, {
		"_id" : mainCusterChild6,
		"board": boardId,
		"children" : [mainCusterChild6Child],
		"collapsed" : true,
		"comments" : [],
		"content" : "Each card has a settings icon in the top right, that allows you to resize, lock and delete a card.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 27,
		"yPos" : 367,
		"zPos" : 6
	}, {
		"_id" : mainCusterChild6Child,
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "Groups also have a settings icon, that lets you dot vote on the cards in a group.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainCusterChild6,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 10,
		"yPos" : 40,
		"zPos" : 1
	}, {
		"_id" : mainCusterChild5,
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "You can read more about dot voting <a href=\"http://www.gogamestorm.com/?p=348\">here.</a>",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : mainClusterId,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 10,
		"yPos" : 40,
		"zPos" : 5
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "You can type HTML to create <a href=\"http://www.gogamestorm.com/\">links</a>, <strong>bold</strong> and <em>italic</em> text.",
		"created" : new Date(),
		"height" : null,
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : null,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"width" : null,
		"xPos" : 19,
		"yPos" : 629,
		"zPos" : 6
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "And <h1>BIG TYPE!</h1>",
		"created" : new Date(),
		"height" : null,
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : null,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"width" : null,
		"xPos" : 26,
		"yPos" : 450,
		"zPos" : 17
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "<iframe frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" mozallowfullscreen=\"true\" webkitallowfullscreen=\"true\" allowfullscreen=\"true\" width=\"160\" height=\"120\" src=\"//app.looplogic.com/davegray/promo-video/embedded?layout=7\" ></iframe>You can even drop in video using an embed code (The best width is 160 pixels)",
		"created" : new Date(),
		"height" : null,
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : null,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"width" : null,
		"xPos" : 248,
		"yPos" : 655,
		"zPos" : 7
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "What else can you do?",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 22,
		"yPos" : 582,
		"zPos" : 5
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "In the top bar there is a settings icon where you can <strong>unlock</strong> cards, <strong>save a copy</strong> of your board, or <strong>export</strong> your board as text, HTML or <a href=\"http://en.wikipedia.org/wiki/OPML\">OPML</a>",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 685,
		"yPos" : 452,
		"zPos" : 10
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "There are buttons at the top right where you can <strong>share</strong> your board, or <strong>give us feedback</strong> and ideas. You can also contact us there for <strong>help</strong> if you need it.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 685,
		"yPos" : 582,
		"zPos" : 8
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "e1b83442-71f6-1318-98cd-3429ac89ff4d.png",
		"created" : new Date(),
		"height" : 332,
		"isLocked" : true,
		"isVoting" : false,
		"title" : "",
		"type" : "image/png",
		"votesReceived" : 0,
		"width" : 540,
		"xPos" : 542,
		"yPos" : 58,
		"zPos" : 0
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "Resize a card and lock it to create a background.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 479,
		"yPos" : 74,
		"zPos" : 1
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "You can unlock it in the settings icon at the top of the board. We did it this way so people don't unlock boards by accident (I mean, you locked it for a reason, right?)",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 477,
		"yPos" : 199,
		"zPos" : 3
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "This <a href=\"http://www.businessmodelgeneration.com/canvas\">Business Model Canvas</a> is locked.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 477,
		"yPos" : 137,
		"zPos" : 2
	}, {
		"_id" : secondClusterChild,
		"board": boardId,
		"children" : [],
		"collapsed" : true,
		"comments" : [],
		"content" : "Use control-plus or control-minus to <strong>zoom in and out</strong> (Apple-plus or Apple-minus on Macs)",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : secondCluster,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 254,
		"yPos" : 548,
		"zPos" : 1
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "If you know HTML, play around. You might be surprised what works!",
		"created" : new Date(),
		"height" : null,
		"isLocked" : false,
		"isVoting" : false,
		"parentId" : null,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"width" : null,
		"xPos" : 23,
		"yPos" : 713,
		"zPos" : 14
	}, {
		"_id" : secondCluster,
		"board": boardId,
		"children" : [secondClusterChild],
		"collapsed" : false,
		"comments" : [],
		"content" : "Other stuff",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 889,
		"yPos" : 445,
		"zPos" : 9
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "<h3>Share your board! That's when you will start to feel the real-time collaborative power of Boardthing!</h3>",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 464,
		"yPos" : 454,
		"zPos" : 16
	}, {
		"board": boardId,
		"children" : [],
		"collapsed" : false,
		"comments" : [],
		"content" : "Double click a card to edit the text.",
		"created" : new Date(),
		"isLocked" : false,
		"isVoting" : false,
		"title" : "",
		"type" : "text",
		"votesReceived" : 0,
		"xPos" : 25,
		"yPos" : 374,
		"zPos" : 13
	}];

	return welcomeCards;
}
